global:
  imageRegistry: zot.day0.sololab
exporter:
  configFiles:
    config:
      modules:
        http_2xx:
          prober: http
          timeout: 5s
          http:
            valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
            follow_redirects: true
            preferred_ip_protocol: "ip4"
            tls_config:
              insecure_skip_verify: true
  flags:
    web:
      listen-address: 127.0.0.1:9115

  podLabels:
    traefik.enable: true
    traefik.http.routers.prometheus-blackbox-exporter-redirect.entrypoints: web
    traefik.http.routers.prometheus-blackbox-exporter-redirect.rule: Host(`prometheus-blackbox-exporter.day1.sololab`)
    traefik.http.routers.prometheus-blackbox-exporter-redirect.middlewares: toHttps@file
    traefik.http.routers.prometheus-blackbox-exporter-redirect.service: prometheus-blackbox-exporter

    traefik.http.routers.prometheus-blackbox-exporter.entryPoints: webSecure
    traefik.http.routers.prometheus-blackbox-exporter.rule: Host(`prometheus-blackbox-exporter.day1.sololab`)
    traefik.http.routers.prometheus-blackbox-exporter.tls: true
    traefik.http.routers.prometheus-blackbox-exporter.service: prometheus-blackbox-exporter

    traefik.http.services.prometheus-blackbox-exporter.loadbalancer.server.port: 9115

  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai
