# https://zitadel.com/docs/self-hosting/manage/reverseproxy/traefik
http:
  routers:
    zitadel-login-redirect:
      entrypoints: web
      rule: Host(`zitadel.day0.sololab`) && PathPrefix(`/ui/v2/login`)
      middlewares: toHttps@file
      service: zitadel-login
    zitadel-login:
      entrypoints: webSecure
      rule: Host(`zitadel.day0.sololab`) && PathPrefix(`/ui/v2/login`)
      tls: {}
      service: zitadel-login
  services:
    zitadel-login:
      loadbalancer:
        passHostHeader: true
        servers:
          - url: "http://127.0.0.1:3000"
