vault:
  ## hashicorp vault image
  ## ref: https://hub.docker.com/r/hashicorp/vault/tags/
  ## @param vault.image.registry vault image registry
  ## @param vault.image.repository vault image repository
  ## @param vault.image.tag vault image tag (immutable tags are recommended)
  ## @param vault.image.digest vault image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag image tag (immutable tags are recommended)
  ## @param vault.image.pullPolicy vault image pull policy
  ## @param vault.image.pullSecrets vault image pull secrets
  ##
  image:
    registry: zot.mgmt.sololab
    repository: hashicorp/vault
    tag: 1.16.2

  ## @param vault.configFiles config file to start vault, the sub config block will convert to json and injected as ConfigMap
  ## You can add whatever sub items under this block
  ## ref: https://developer.hashicorp.com/vault/docs/configuration
  ## ref: https://developer.hashicorp.com/vault/tutorials/operations/configure-vault#config
  configFiles:
    listeners:
      listener:
        - tcp:
            tls_disable: false
            address: "[::]:8200"
            cluster_address: "[::]:8201"
            # https://github.com/hashicorp/vault/blob/2718994242f94df3dc90215b2ecbc5d4198d9e3c/website/content/docs/platform/k8s/helm/examples/standalone-tls.mdx#L191
            tls_cert_file: /vault/userconfig/vault-server-tls/tls.crt
            tls_key_file: /vault/userconfig/vault-server-tls/tls.key
            tls_disable_client_certs: true

  ## @param vault.podAnnotations Annotations for %%MAIN_CONTAINER_NAME%% pods
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ## ref: https://github.com/containers/podman/discussions/22378
  ##
  podAnnotations:
    io.podman.annotations.userns: keep-id:uid=100,gid=1000
