global:
  imageRegistry: zot.day0.sololab
dufs:
  podLabels:
    traefik.enable: true
    traefik.http.routers.dufs-http.entrypoints: web
    traefik.http.routers.dufs-http.rule: Host(`dufs.day0.sololab`)
    traefik.http.routers.dufs-http.service: dufs

    traefik.http.routers.dufs.entrypoints: webSecure
    traefik.http.routers.dufs.rule: Host(`dufs.day0.sololab`)
    traefik.http.routers.dufs.tls: true
    traefik.http.routers.dufs.service: dufs

    traefik.http.services.dufs.loadbalancer.server.port: 5001

  config:
    bind: 127.0.0.1
    port: 5001
    auth:
      - admin:admin@/:rw
      - user:pass@/private:ro
      - "@/public"
