accessLog: {}
api:
  dashboard: true
entryPoints:
  traefik:
    address: :8080
  web:
    address: :80
    forwardedHeaders:
      trustedIPs:
        - 0.0.0.0/0
    proxyProtocol:
      trustedIPs:
        - 192.168.255.1
        - 192.168.255.2
        - 192.168.255.20
  webSecure:
    address: :443
    forwardedHeaders:
      trustedIPs:
        - 0.0.0.0/0
    proxyProtocol:
      trustedIPs:
        - 192.168.255.1
        - 192.168.255.2
        - 192.168.255.20
global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: INFO
metrics:
  prometheus:
    manualRouting: true
ping: {}
providers:
  # consulCatalog:
  #   endpoint:
  #     address: consul.day1.sololab:8501
  #     datacenter: dc1
  #     scheme: https
  #     tls:
  #       ca: /etc/traefik/tls/ca.crt
  #   exposedByDefault: false
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    useBindPortIP: false
  file:
    directory: /etc/traefik/dynamic
    watch: true
serversTransport:
  insecureSkipVerify: false
  rootCAs:
    - /etc/traefik/tls/ca.crt
