http:
  middlewares:
    toHttps:
      redirectScheme:
        scheme: https
        permanent: true
    userPass:
      basicAuth:
        users:
          - admin:$apr1$/F5ai.wT$7nFJWh4F7ZA0qoY.JZ69l1

tls:
  certificates:
    - certFile: /secrets/tls/consul.crt
      keyFile: /secrets/tls/consul.key
