http:
  routers:
    loki-redirect:
      entryPoints:
        - web
      middlewares:
        - toHttps@file
      rule: Host(`loki.day1.sololab`)
      service: loki
    loki:
      entryPoints:
        - webSecure
      rule: Host(`loki.day1.sololab`)
      service: loki
      tls: true
  services:
    loki:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:3100/"
