global:
  imageRegistry: zot.day0.sololab
loki:
  hostNetwork: false
  containerPorts:
    - name: http
      containerPort: 3100
      hostPort: 3100
      hostIP: 127.0.0.1
      protocol: TCP
    - name: grpc
      containerPort: 9095
      hostPort: 9095
      hostIP: 127.0.0.1
      protocol: TCP
  resourcesPreset: "small"

  config:
    # https://grafana.com/docs/grafana-cloud/visualizations/simplified-exploration/logs/access/
    limits_config:
      allow_structured_metadata: true
      volume_enabled: true
    pattern_ingester:
      enabled: true
    # common:
    #   instance_interface_names:
    #     - lo
    schema_config:
      ## @param loki.config.schema_config.configs list of period_configs
      ##
      configs:
        - from: 2025-01-01
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: index_
            period: 24h

    ## loki official image cannot handle tls well by itself,
    ## reason: failed to run local healthcheck with wget if tls configed
    ## error message: tls: invalid ClientKeyExchange message
    # server:
    #   http_listen_address: 127.0.0.1
    #   grpc_listen_address: 127.0.0.1
    #   # http_tls_config:
    #   #   # https://pkg.go.dev/crypto/tls#ClientAuthType
    #   #   client_auth_type: VerifyClientCertIfGiven
    #   #   client_ca_file: /etc/loki/certs/ca.crt
    #   #   cert_file: /etc/loki/certs/loki.crt
    #   #   key_file: /etc/loki/certs/loki.key

    ## @param loki.config.storage_config config storage backend for storing chunks of log data
    ## ref: https://grafana.com/docs/loki/v3.6.x/configure/#storage_config
    ## ref: https://grafana.com/docs/loki/v3.6.x/operations/storage/tsdb/#single-store-tsdb-tsdb
    ##
    storage_config:
      tsdb_shipper:
        active_index_directory: /var/loki/tsdb-index
        cache_location: /var/loki/tsdb-cache
      use_thanos_objstore: true
      object_store:
        # https://grafana.com/docs/loki/v3.6.x/configure/#thanos_object_store_config
        s3:
          # https://github.com/cloudlena/s3manager/issues/7
          endpoint: minio-api.day0.sololab
          bucket_name: loki
          access_key_id: # set from terraform data
          secret_access_key: # set from terraform data
          # s3forcepathstyle: true
          http:
            tls_ca_path: /etc/loki/certs/ca.crt
    ui:
      enabled: true

  args:
    - -config.file=/etc/loki/local-config.yaml

  # podLabels:
  #   traefik.enable: true
  #   traefik.http.routers.loki-redirect.entrypoints: web
  #   traefik.http.routers.loki-redirect.rule: Host(`loki.day1.sololab`)
  #   traefik.http.routers.loki-redirect.middlewares: toHttps@file
  #   traefik.http.routers.loki-redirect.service: loki

  #   traefik.http.routers.loki.entrypoints: webSecure
  #   traefik.http.routers.loki.rule: Host(`loki.day1.sololab`)
  #   traefik.http.routers.loki.tls: true
  #   traefik.http.routers.loki.service: loki

  #   traefik.http.services.loki.loadbalancer.server.port: 3100

  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai
