global:
  imageRegistry: zot.vyos.sololab
lldap:
  podLabels:
    traefik.enable: true
    traefik.http.routers.lldap-web-redirect.entrypoints: web
    traefik.http.routers.lldap-web-redirect.rule: "Host(`lldap.day0.sololab`)"
    traefik.http.routers.lldap-web-redirect.middlewares: toHttps@file
    traefik.http.routers.lldap-web.entryPoints: webSecure
    traefik.http.routers.lldap-web.rule: "Host(`lldap.day0.sololab`)"
    traefik.http.routers.lldap-web.tls: true
    traefik.http.routers.lldap-web.service: lldap-web
    traefik.http.services.lldap-web.loadbalancer.server.port: 17170
    # traefik.http.services.lldap-web.loadbalancer.server.url: http://127.0.0.1:17170
  containerSecurityContext:
    sysctls:
      - name: net.ipv4.ip_unprivileged_port_start
        value: "389"
  config:
    # ldap_host: 192.168.255.10
    # ldap_port: 389
    # https://github.com/lldap/lldap/blob/1f89059c84d700ca198b2785657f33f438ea3e11/server/src/healthcheck.rs#L74
    # health check function only support localhost
    http_host: 127.0.0.1
    # http_port: 17170
    jwt_secret: REPLACE_WITH_RANDOM
    ldap_base_dn: dc=root,dc=sololab
    ldap_user_dn: admin
    ldap_user_pass: P@ssw0rd
    database_url: sqlite:///data/persistence/users.db?mode=rwc
    ldaps_options:
      enabled: true
      # port: 636
      cert_file: /data/certs/cert.pem
      key_file: /data/certs/key.pem
